version: '3.8'

services:
  vitejs:
    image: node:21-alpine3.18
    container_name: vitejs
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        cd portfolio
        npm run dev
    user: '1000:1000'
    volumes:
      - /app/node_modules
      - ./django/vitejs:/app
    ports:
      - '3300:3000'
    restart: unless-stopped
  nextjs:
    image: node:21-alpine3.18
    container_name: nextjs
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        tail -F /dev/null
    user: '1000:1000'
    volumes:
      - /app/node_modules
      - ./nextjs:/app
    ports:
      - '3001:3000'
    restart: unless-stopped
  angularjs:
    image: node:20.6-alpine3.17
    container_name: angularjs
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        tail -F /dev/null
    # user: '1000:1000'
    volumes:
      - /app/node_modules
      - ./angularjs:/app
    ports:
      - '4200:4200'
    restart: unless-stopped
  reactjs:
    image: node:20.6-alpine3.17
    container_name: reactjs
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        tail -F /dev/null
    # user: '1000:1000'
    volumes:
      - /app/node_modules
      - ./reactjs:/app
    ports:
      - '3000:3000'
      - '4000:4000'
    restart: unless-stopped

  expressjs:
    image: node:19.0-alpine3.16
    container_name: expressjs
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        tail -F /dev/null
    # user: "1000:1000"
    volumes:
      - /app/node_modules
      - ./expressjs:/app
    ports:
      - '5000:5000'
    restart: unless-stopped
    # setting up environment variables
    environment:
      - NODE_ENV=development
      # {{ with secret "kv/data/POSTGRESQL" }}
      - pg_master_database=portfolio
      - pg_master_user={{ .Data.data.POSTGRESQL_USERNAME }}
      - pg_master_password={{ .Data.data.POSTGRESQL_PASSWORD }}
      - pg_master_host={{ .Data.data.POSTGRESQL_MASTER_HOST }}
      - pg_master_port=5432
      # {{ end }}

  jsonserver:
    image: node:17.7.2-alpine3.14
    container_name: jsonserver
    command: sh -c "tail -F /dev/null"
    user: '1000:1000'
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./jsonserver:/app
    ports:
      - '3001:3001'

  django:
    image: python:3.12.0b4-bookworm
    container_name: django
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        tail -F /dev/null
    # user: "1000:1000"
    volumes:
      - ./python:/app
    ports:
      - '8000:8000'
    restart: unless-stopped
    # env_file: .env
    environment:
      - DJANGO_DEBUG=True
      # {{ with secret "kv/data/POSTGRESQL" }}
      - pg_master_database=portfolio
      - pg_master_user={{ .Data.data.POSTGRESQL_USERNAME }}
      - pg_master_password={{ .Data.data.POSTGRESQL_PASSWORD }}
      - pg_master_host={{ .Data.data.POSTGRESQL_MASTER_HOST }}
      - pg_master_port=5432
      # {{ end }}

  django2:
    build:
      context: ./django/
      dockerfile: Dockerfile.dev
    container_name: django2
    volumes:
      - ./django:/home/feroz/app
    ports:
      - '8300:8000'
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=True
      # {{ with secret "kv/data/django_token" }}
      - VAULT_ADDR={{ .Data.data.VAULT_ADDR }}
      - VAULT_TOKEN={{ .Data.data.VAULT_TOKEN }}
      # {{ end }}
