services:
  expressjs-api:
    image: 155097172472.dkr.ecr.us-east-2.amazonaws.com/portfolio-expressjs:2024.04.25.130939446
    container_name: expressjs-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
